name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USER: ${{ secret.BS_USER }}
            BROWSERSTACK_KEY: ${{ secret.BS_KEY }}
          run: npx wdio config/wdio.android.bs.conf.js --spec D:\Automation\webdriverio-appium-v8\test\specs\android\addnotescreen.spec.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
